// Ver 2026-09-23 03:05, by pi

// The help guide's language table: every string that differs between the
// English and Chinese variants of help.html lives here, keyed by the
// {{T:key}} tokens embedded in that single template. Structure, styles, the
// JS fill engine and the agent config snippets stay in the template itself
// (the snippets' code — and even their comments — are language-neutral
// except codex-toml's two, which are table entries too).
//
// The two maps must have identical key sets; TestHelpStrings_KeySetsMatch
// pins that parity, so the language tables cannot drift apart. Values are
// authored page content
// (they may carry inline HTML like <code>); user input never enters them.
// {0}..{4} inside a value are filled client-side by help.html's fmtT for
// the handful of messages that interpolate live data.
package server

// helpStringsEN: English copy of the agent configuration guide.
var helpStringsEN = map[string]string{
	"html-lang":            "en",
	"title":                "VMR Console — Help",
	"page-head":            "Agent Configuration Guides",
	"lede":                 `Point any AI coding agent at this VMR instance: the base URL below, an API key from your administrator, and a virtual model name are all most clients need. Where an agent supports it, also configure context window (e.g. <code>200k</code>), reasoning effort (<code>high</code>, <code>budget_tokens</code>) and vision (<code>image</code>) to match VMR's model metadata — the per-client notes live inside each guide below. <a href="/help.zh.html" lang="zh" title="切换到中文版指南">中文版指南 →</a>`,
	"conn-title":           "Connection",
	"copy":                 "Copy",
	"copied":               "Copied ✓",
	"label-models":         "models",
	"loading":              "loading…",
	"label-auth":           "auth",
	"auth-note":            `<code>Authorization: Bearer &lt;key&gt;</code> (or <code>x-api-key</code> for Anthropic-protocol clients) — provisioned by your administrator (<code>api_keys:</code> in config.yaml), never shown on this page.`,
	"chk-idle":             "no key stored",
	"chk-idle-detail":      `No API key in this browser yet — agents below need one in the <code>Authorization: Bearer</code> header.`,
	"chk-btn":              "Check connection",
	"set-key-btn":          "Set key",
	"qr-title":             "Quick Reference",
	"qr-hint":              "Which protocol to use, and where to configure it. Click an agent to open its guide below.",
	"qr-th-proto":          "Protocol",
	"qr-th-config":         "Config location",
	"qr-cursor-config":     "Settings → Models; env",
	"anthropic-head":       "Anthropic Messages Protocol",
	"anthropic-hint":       `Agents that natively speak the Anthropic Messages API. Point the base URL at VMR's Anthropic-compatible endpoint; the key is sent via the <code>x-api-key</code> header.`,
	"openai-head":          "OpenAI Completions Protocol",
	"openai-hint":          `Agents that natively speak the OpenAI Chat Completions API. Point the base URL at VMR's OpenAI-compatible endpoint; the key is sent via the <code>Authorization: Bearer</code> header.`,
	"official-docs":        "Official Docs →",
	"cfg-env-file":         "~/.bashrc, ~/.zshrc, or shell profile (environment variables)",
	"cc-desc":              `Anthropic's official terminal coding agent. Route through VMR using environment variables or <code>~/.claude/settings.json</code>. Claude Code automatically connects to <code>ANTHROPIC_BASE_URL</code>. Tune reasoning budget with <code>MAX_THINKING_TOKENS</code> (fixed budget) or <code>CLAUDE_CODE_EFFORT_LEVEL</code> / <code>/effort</code> (adaptive reasoning).`,
	"codex-desc":           `OpenAI's official terminal coding agent. Route through VMR via environment variables or <code>~/.codex/config.toml</code>. Configure <code>model_reasoning_effort</code> (minimal / low / medium / high / xhigh) and <code>model_context_window</code> in <code>config.toml</code> to manage memory and thinking depth.`,
	"codex-toml-comment-1": `# Model and provider defaults`,
	"codex-toml-comment-2": `# VMR custom provider (wire_api: "responses" for /v1/responses, or "chat" for /v1/chat/completions)`,
	"openclaw-desc":        `An open-source, Claude Code-compatible terminal agent. Supports OpenAI-compatible API endpoints. Configure context window, vision, reasoning effort, and thinking budget via environment variables or <code>config.yaml</code>.`,
	"opencode-desc":        `A terminal-based AI coding agent (<a href="https://opencode.ai" target="_blank" rel="noopener">opencode.ai</a>). Configure a custom provider in <code>opencode.json</code> with <code>limit</code> (context &amp; output), <code>modalities</code> (vision), and <code>reasoning</code> flags.`,
	"opencode-cfg-file":    "opencode.json (project root) or ~/.config/opencode/opencode.json",
	"cursor-summary":       "Cursor (IDE &amp; CLI)",
	"cursor-desc":          `Cursor supports routing AI requests to custom OpenAI-compatible endpoints directly from its IDE settings or terminal agent (<code>cursor-agent</code>). In the IDE, override the OpenAI Base URL and add your VMR virtual model name.`,
	"cursor-cfg-ide":       "Cursor IDE settings (UI configuration)",
	"cursor-cfg-cli":       "Terminal CLI (cursor-agent)",
	"hermes-desc":          `A fast, extensible terminal AI coding agent. Supports OpenAI-compatible endpoints with configurable context window, max tokens, reasoning depth, and vision flags.`,
	"hermes-cfg-file":      "Environment variables, or ~/.hermes/config.yaml",
	"pi-desc":              `Pi is a minimalist, extensible terminal AI coding agent (<a href="https://github.com/earendil-works/pi-mono" target="_blank" rel="noopener">earendil-works/pi-mono</a>). Add VMR as a custom provider in <code>~/.pi/agent/models.json</code>, specifying <code>contextWindow</code>, <code>maxTokens</code>, <code>input</code> (modalities), and <code>reasoning</code> flags. Pi keys providers by API protocol, so VMR appears as <code>vmr-openai</code> and/or <code>vmr-anthropic</code> — both <code>openai-completions</code> and <code>anthropic-messages</code> are supported.`,
	"pi-cfg-file":          "~/.pi/agent/models.json (create if not exists)",
	"pi-note":              `Virtual model names, context windows and token budgets in this block are refreshed from the live <code>/status</code> model list once it is readable — one provider entry per protocol VMR actually serves.`,
	"workbuddy-desc":       `A terminal-based AI coding assistant. Configure via environment variables or <code>~/.workbuddy/config.yaml</code>. Supports context length, max output tokens, vision input, and reasoning effort.`,
	"workbuddy-cfg-file":   "~/.workbuddy/config.yaml or .workbuddy.yaml",
	"trouble-title":        "Troubleshooting",
	"trouble-1":            `<p>• <b>401 from every request</b> → the key in <code class="mono">Authorization: Bearer</code> must match an entry of <code class="mono">api_keys:</code>.</p>`,
	"trouble-2":            `<p>• <b>Unknown model</b> → virtual models are per-protocol; check <a href="/status.html#models">Overview → Virtual Models &amp; Endpoint Topology</a> for the protocol each name answers on.</p>`,
	"trouble-3":            `<p>• <b>401s appearing mid-session</b> → vmr was reloaded with a changed <code class="mono">api_keys:</code>; re-set the key (🔑 button, stored in this browser only).</p>`,
	"trouble-4":            `<p>• <b>A request feels slow or hangs</b> → open <a href="/status.html#live">Overview → Live Requests</a>: a red <i>stalled</i> badge means no upstream byte for over 5s; a long <i>queued</i> elapsed means the concurrency gate is full.</p>`,
	"trouble-5":            `<p>• <b>All requests suddenly fail over</b> → check <a href="/status.html#models">endpoint health</a> for cooldowns, and <a href="/status.html#quota">Quota Budgets</a> for a saturated gate.</p>`,
	"trouble-6":            `<p>• <b>A request just failed and you want to know why</b> → <a href="/status.html#failures">Overview → Recent Failures</a> lists the last failures with the router's own error class; the class chips double as a filter when one class floods the buffer.</p>`,
	"no-models":            "(no models configured)",
	"unconstrained":        "unconstrained",
	// Rephrased without the possessive so the value is safe inside a
	// single-quoted JS string literal (the tokens live in page script).
	"m-title-ctx":       "Largest max_context_tokens across the endpoints of this model",
	"m-title-caps":      "Union of capabilities across the endpoints of this model — not every endpoint necessarily has every one; routing picks whichever endpoint actually supports what a request needs",
	"reveal-key":        "🔑 enter API key to reveal",
	"chk-ok-state":      "reachable",
	"chk-ok-detail":     `<code>GET /status</code> returned <b>{0}</b> virtual model(s) across <b>{1}</b> protocol(s).`,
	"chk-401-state":     "401 — key required",
	"chk-401-detail":    `This instance requires an API key. Set one (🔑) to load the live model list.`,
	"chk-err-state":     "unreachable",
	"chk-err-detail":    `<code>GET /status</code> failed — network error or non-200 response.`,
	"chk-stored-detail": `Key stored in this browser. Press <b>Check connection</b> to verify it against <code>GET /status</code>.`,
	"chk-stored-state":  "key {0} stored",
	"uptime":            "up {0}",
	"footer-id":         `Virtual Model Router (VMR) · {0} · pid {1} · {2} · {3} · listen {4}`,
	"toast-ok":          "Connection OK — {0} virtual model(s)",
	"toast-auth":        "API key required or invalid",
	"toast-fail":        "Connection check failed",
}

// helpStringsZH: 中文文案。键集合必须与 helpStringsEN 完全一致
// （TestHelpStrings_KeySetsMatch 守卫）；{0}..{4} 占位符语义也必须一一对应。
var helpStringsZH = map[string]string{
	"html-lang":            "zh",
	"title":                "VMR 控制台 — 帮助",
	"page-head":            "Agent 配置指南",
	"lede":                 `将任何 AI 编程 Agent 指向本 VMR 实例：使用下方的 Base URL、管理员下发的 API 密钥以及虚拟模型名即可接入。客户端支持的前提下，可进一步配置上下文窗口（例如 <code>200k</code>）、推理深度（<code>high</code>、<code>budget_tokens</code>）与多模态视觉（<code>image</code>）以匹配 VMR 的模型元数据 —— 逐客户端说明见下方各指南。<a href="/help.html" lang="en" title="Switch to English guide">English guide →</a>`,
	"conn-title":           "连接信息",
	"copy":                 "复制",
	"copied":               "已复制 ✓",
	"label-models":         "模型",
	"loading":              "加载中…",
	"label-auth":           "鉴权",
	"auth-note":            `<code>Authorization: Bearer &lt;key&gt;</code>（Anthropic 协议客户端为 <code>x-api-key</code>）—— 由管理员在 config.yaml 的 <code>api_keys:</code> 中下发，本页绝不显示密钥明文。`,
	"chk-idle":             "尚未存储密钥",
	"chk-idle-detail":      `本浏览器还没有 API 密钥 —— 下方各客户端需要在 <code>Authorization: Bearer</code> 请求头中携带它。`,
	"chk-btn":              "检查连接",
	"set-key-btn":          "设置密钥",
	"qr-title":             "速查表",
	"qr-hint":              "一图速览：用哪个协议，在哪里配置。点击 Agent 名称可打开下方对应指南。",
	"qr-th-proto":          "协议",
	"qr-th-config":         "配置位置",
	"qr-cursor-config":     "设置 → Models; 环境变量",
	"anthropic-head":       "Anthropic Messages 协议",
	"anthropic-hint":       `原生使用 Anthropic Messages API 的 Agent。将 Base URL 指向 VMR 的 Anthropic 兼容端点；API 密钥通过 <code>x-api-key</code> 请求头发送。`,
	"openai-head":          "OpenAI Completions 协议",
	"openai-hint":          `原生使用 OpenAI Chat Completions API 的 Agent。将 Base URL 指向 VMR 的 OpenAI 兼容端点；API 密钥通过 <code>Authorization: Bearer</code> 请求头发送。`,
	"official-docs":        "官方文档 →",
	"cfg-env-file":         "~/.bashrc、~/.zshrc 或 shell 配置（环境变量）",
	"cc-desc":              `Anthropic 官方的终端编程 Agent。可通过环境变量或 <code>~/.claude/settings.json</code> 路由到 VMR。Claude Code 会自动连接 <code>ANTHROPIC_BASE_URL</code>。可通过 <code>MAX_THINKING_TOKENS</code>（固定 Token 数）或 <code>CLAUDE_CODE_EFFORT_LEVEL</code> / <code>/effort</code>（自适应思考）调节推理深度。`,
	"codex-desc":           `OpenAI 官方的终端编程 Agent。可通过环境变量或 <code>~/.codex/config.toml</code> 路由到 VMR。在 <code>config.toml</code> 中配置 <code>model_reasoning_effort</code>（minimal / low / medium / high / xhigh）和 <code>model_context_window</code> 来管理上下文与思考深度。`,
	"codex-toml-comment-1": `# 模型与提供商默认配置`,
	"codex-toml-comment-2": `# VMR 自定义提供商（wire_api: "responses" 使用 /v1/responses，或 "chat" 使用 /v1/chat/completions）`,
	"openclaw-desc":        `一个开源、兼容 Claude Code 的终端 Agent。支持 OpenAI 兼容的 API 端点。通过环境变量或 <code>config.yaml</code> 配置文件配置上下文窗口、视觉能力、推理深度以及思考预算。`,
	"opencode-desc":        `一个终端 AI 编程 Agent（<a href="https://opencode.ai" target="_blank" rel="noopener">opencode.ai</a>）。在 <code>opencode.json</code> 中配置自定义提供商，声明 <code>limit</code>（上下文与输出）、<code>modalities</code>（多模态视觉）及 <code>reasoning</code> 开关。`,
	"opencode-cfg-file":    "opencode.json（项目根目录）或 ~/.config/opencode/opencode.json",
	"cursor-summary":       "Cursor（IDE 与 CLI）",
	"cursor-desc":          `Cursor 支持在 IDE 设置中直接覆盖 OpenAI Base URL，或在终端使用 <code>cursor-agent</code> 将请求路由到自定义 OpenAI 兼容端点。在 IDE 中覆盖 OpenAI Base URL 并添加 VMR 虚拟模型名即可。`,
	"cursor-cfg-ide":       "Cursor IDE 设置（界面配置）",
	"cursor-cfg-cli":       "终端 CLI（cursor-agent）",
	"hermes-desc":          `一个快速、可扩展的终端 AI 编程 Agent。支持通过环境变量或 <code>~/.hermes/config.yaml</code> 配置 OpenAI 兼容端点的上下文长度、最大输出、视觉开关及推理深度。`,
	"hermes-cfg-file":      "环境变量，或 ~/.hermes/config.yaml",
	"pi-desc":              `Pi 是一个极简、可扩展的终端 AI 编程 Agent（<a href="https://github.com/earendil-works/pi-mono" target="_blank" rel="noopener">earendil-works/pi-mono</a>）。在 <code>~/.pi/agent/models.json</code> 中将 VMR 注册为自定义 provider，指定 <code>contextWindow</code>、<code>maxTokens</code>、<code>input</code>（多模态能力）与 <code>reasoning</code> 开关。Pi 按 API 协议对 provider 分键，VMR 可配置为 <code>vmr-openai</code> 与/或 <code>vmr-anthropic</code> —— 同时支持 <code>openai-completions</code> 与 <code>anthropic-messages</code>。`,
	"pi-cfg-file":          "~/.pi/agent/models.json（如不存在则创建）",
	"pi-note":              `一旦 <code>/status</code> 可读，此代码块中的虚拟模型名、上下文窗口与 Token 预算会自动根据实时模型列表刷新 —— VMR 实际服务的协议每种生成一个 provider 条目。`,
	"workbuddy-desc":       `一个基于终端的 AI 编程助手。通过环境变量或 <code>~/.workbuddy/config.yaml</code> 配置。支持上下文长度、最大输出 Token、多模态视觉输入及推理深度。`,
	"workbuddy-cfg-file":   "~/.workbuddy/config.yaml 或 .workbuddy.yaml",
	"trouble-title":        "故障排查",
	"trouble-1":            `<p>• <b>所有请求都返回 401</b> → <code class="mono">Authorization: Bearer</code> 中的密钥必须与 <code class="mono">api_keys:</code> 中的某一匹配。</p>`,
	"trouble-2":            `<p>• <b>模型不存在</b> → 虚拟模型按协议区分；到 <a href="/status.html#models">Overview → Virtual Models &amp; Endpoint Topology</a> 查看每个名字应答的协议。</p>`,
	"trouble-3":            `<p>• <b>会话中途突然 401</b> → vmr 在密钥变更后被重载过；重新设置密钥（🔑 按钮，仅存储在本浏览器）。</p>`,
	"trouble-4":            `<p>• <b>请求很慢或卡住</b> → 打开 <a href="/status.html#live">Overview → Live Requests</a>：红色 <i>stalled</i> 标记表示超过 5 秒没有上游字节；<i>queued</i> 计时很长表示并发闸门已满。</p>`,
	"trouble-5":            `<p>• <b>所有请求突然全部故障转移</b> → 到 <a href="/status.html#models">端点健康</a> 查看 cooldown，到 <a href="/status.html#quota">Quota Budgets</a> 查看是否配额耗尽。</p>`,
	"trouble-6":            `<p>• <b>请求刚失败，想知道为什么</b> → <a href="/status.html#failures">Overview → Recent Failures</a> 列出最近的失败及其路由错误类别；当某一类错误刷屏时，类别芯片可点击过滤。</p>`,
	"no-models":            "（尚未配置模型）",
	"unconstrained":        "不限制",
	"m-title-ctx":          "该虚拟模型所有 endpoint 中最大的 max_context_tokens",
	"m-title-caps":         "该虚拟模型所有 endpoint 能力的并集——不代表每个 endpoint 都同时具备；实际路由会挑选真正支持该请求所需能力的 endpoint",
	"reveal-key":           "🔑 输入 API 密钥以展示",
	"chk-ok-state":         "可连通",
	"chk-ok-detail":        `<code>GET /status</code> 返回了 <b>{1}</b> 种协议下的 <b>{0}</b> 个虚拟模型。`,
	"chk-401-state":        "401 — 需要密钥",
	"chk-401-detail":       `本实例需要 API 密钥。设置密钥（🔑）以加载实时模型列表。`,
	"chk-err-state":        "无法连通",
	"chk-err-detail":       `<code>GET /status</code> 失败 —— 网络错误或非 200 响应。`,
	"chk-stored-detail":    `密钥已存储在本浏览器。点击 <b>检查连接</b> 向 <code>GET /status</code> 发起校验。`,
	"chk-stored-state":     "已存密钥 {0}",
	"uptime":               "已运行 {0}",
	"footer-id":            `Virtual Model Router (VMR) · {0} · pid {1} · {2} · {3} · 监听 {4}`,
	"toast-ok":             "连接成功 —— {0} 个虚拟模型",
	"toast-auth":           "API 密钥缺失或无效",
	"toast-fail":           "连接检查失败",
}
