// Ver 2026-08-29, by Sonnet 5

// Pairs with internal/report/toolwaste_html.go — the standalone
// tool-schema-waste card (`{out}/tool-waste.html`, written by `vmr analyze`
// whenever the report has tool data). Fixed UI strings only; every number
// comes from the report's own rep.Tools rows.
package i18n

import "fmt"

// ToolWasteText is the tool-waste card's chrome, in one language.
type ToolWasteText struct {
	DocTitle      string
	RecorderBar   string
	HeroPct       func(pct string) string
	HeroCaption   string
	StatShipped   string
	StatDead      string
	StatTokens    string
	StatShapes    string
	ColShape      string
	ColRequests   string
	ColUsage      string
	ColWaste      string
	UsedCalled    func(called, declared int) string
	Footnote      string
	GeneratedNote string
}

// ToolWaste returns the card chrome text for lang.
func ToolWaste(lang Lang) ToolWasteText {
	if lang == ZH {
		return ToolWasteText{
			DocTitle:    "工具 Schema 浪费审计",
			RecorderBar: "VMR · 工具 SCHEMA 审计",
			HeroPct:     func(pct string) string { return pct },
			HeroCaption: "本报表窗口内你随每次请求发出的工具定义字节，从未被调用的占比",
			StatShipped: "累计发出",
			StatDead:    "其中死重",
			StatTokens:  "≈ 浪费 token",
			StatShapes:  "工具集形态",
			ColShape:    "工具集形态",
			ColRequests: "请求数",
			ColUsage:    "实际用 / 声明",
			ColWaste:    "浪费",
			UsedCalled:  func(called, declared int) string { return fmt.Sprintf("%d / %d", called, declared) },
			Footnote: "「形态」= 一组去重后完全相同的工具声明集合。token 数为粗估（工具 schema JSON ≈ 4 字节/token）。" +
				"仅统计本次报表窗口。裁掉从未调用的工具即可省下这部分开销。",
			GeneratedNote: "由 vmr analyze 生成 · 单文件自包含 · 零外部依赖",
		}
	}
	return ToolWasteText{
		DocTitle:    "Tool schema waste audit",
		RecorderBar: "VMR · TOOL SCHEMA AUDIT",
		HeroPct:     func(pct string) string { return pct },
		HeroCaption: "of the tool-definition bytes you shipped on every request this window were for tools never called",
		StatShipped: "Total shipped",
		StatDead:    "Dead weight",
		StatTokens:  "≈ tokens wasted",
		StatShapes:  "Tool-set shapes",
		ColShape:    "Tool-set shape",
		ColRequests: "Requests",
		ColUsage:    "Used / declared",
		ColWaste:    "Waste",
		UsedCalled:  func(called, declared int) string { return fmt.Sprintf("%d / %d", called, declared) },
		Footnote: "A \"shape\" is one deduplicated set of identical tool declarations. Token counts are estimated " +
			"(tool-schema JSON ≈ 4 bytes/token). This report window only. Trimming the never-called tools removes this overhead.",
		GeneratedNote: "Generated by vmr analyze · single self-contained file · zero external dependencies",
	}
}
