// Ver 2026-08-01, by Sonnet 5

// Pairs with internal/story/llm.go (the -compare LLM interpretation layer).
// The system prompt instructs the model which language to answer in, so the
// report's language and the interpretation's language always match.
package i18n

// LLMText is llm.go's text, in one language. SystemPrompt/UserPromptPrefix/
// UserPromptSuffix are the -compare scenario's own (EvidencePack.
// promptSpec); SingleJourney*/Divergence* are llm_single.go/
// llm_divergence.go's Phase 2 scenarios — SectionTitle/SectionDisclaimer/
// CachedNote/NoTextReply are shared across all three (the "this is
// interpretation, not fact" banner and the tool-index no-reply placeholder
// don't vary by scenario).
type LLMText struct {
	SystemPrompt     string
	UserPromptPrefix string
	UserPromptSuffix string

	SingleJourneySystemPrompt     string
	SingleJourneyUserPromptPrefix string
	SingleJourneyUserPromptSuffix string

	DivergenceSystemPrompt     string
	DivergenceUserPromptPrefix string
	DivergenceUserPromptSuffix string

	NoTextReply       string
	SectionTitle      func(model, scope string) string // scope: "" for the only LLM section in a document, else a short label distinguishing it from another in the same document (-compare's overall vs. divergence-point sections)
	SectionDisclaimer func(model string) string
	CachedNote        string

	// ScopeOverall/ScopeDivergence are the scope labels -compare passes to
	// RenderLLMSection for its two possible LLM sections (see SectionTitle) —
	// defined here, not composed ad hoc at the call site, so the label text
	// stays consistent with how DivergenceTitle (story_compare.go) and this
	// package's other "分叉点"/"divergence" wording already read.
	ScopeOverall    string
	ScopeDivergence string
}

func LLM(lang Lang) LLMText {
	if lang == ZH {
		return LLMText{
			SystemPrompt:     llmSystemPromptZH,
			UserPromptPrefix: "以下是两个 Journey 的结构化对比数据：\n\n```json\n",
			UserPromptSuffix: "\n```\n",

			SingleJourneySystemPrompt:     llmSingleJourneySystemPromptZH,
			SingleJourneyUserPromptPrefix: "以下是一个 Journey 的结构化数据（行为剖面指标 + 规则发现的疑似问题清单 + 逐轮工具调用索引）：\n\n```json\n",
			SingleJourneyUserPromptSuffix: "\n```\n",

			DivergenceSystemPrompt:     llmDivergenceSystemPromptZH,
			DivergenceUserPromptPrefix: "以下是两个 Journey 分叉点附近的结构化证据（分叉点本身 + 双方分叉点前后各几步的简要信息）：\n\n```json\n",
			DivergenceUserPromptSuffix: "\n```\n",

			NoTextReply: "(无文本回复)",
			SectionTitle: func(model, scope string) string {
				if scope == "" {
					return "## LLM 解读（模型：" + model + "）\n\n"
				}
				return "## LLM 解读（模型：" + model + " · " + scope + "）\n\n"
			},
			SectionDisclaimer: func(model string) string {
				return "> 以下内容由 `" + model + "` 生成的解读，不是事实层，可能有误，请对照上面的证据表核实。\n"
			},
			CachedNote: "> (命中缓存，未重新调用)\n",

			ScopeOverall:    "整体对比",
			ScopeDivergence: "分叉点",
		}
	}
	return LLMText{
		SystemPrompt:     llmSystemPromptEN,
		UserPromptPrefix: "Here is the structured comparison data for two Journeys:\n\n```json\n",
		UserPromptSuffix: "\n```\n",

		SingleJourneySystemPrompt:     llmSingleJourneySystemPromptEN,
		SingleJourneyUserPromptPrefix: "Here is one Journey's structured data (behavior-profile metrics + the rule-derived suspected-issues list + a per-turn tool-call index):\n\n```json\n",
		SingleJourneyUserPromptSuffix: "\n```\n",

		DivergenceSystemPrompt:     llmDivergenceSystemPromptEN,
		DivergenceUserPromptPrefix: "Here is the structured evidence around two Journeys' divergence point (the divergence point itself, plus a few steps before/after it on each side):\n\n```json\n",
		DivergenceUserPromptSuffix: "\n```\n",

		NoTextReply: "(no text reply)",
		SectionTitle: func(model, scope string) string {
			if scope == "" {
				return "## LLM Interpretation (model: " + model + ")\n\n"
			}
			return "## LLM Interpretation (model: " + model + " · " + scope + ")\n\n"
		},
		SectionDisclaimer: func(model string) string {
			return "> The following was generated by `" + model + "`. It is not the fact layer, may be wrong, and should be checked against the evidence table above.\n"
		},
		CachedNote: "> (cache hit, not re-invoked)\n",

		ScopeOverall:    "overall comparison",
		ScopeDivergence: "divergence point",
	}
}

// llmSystemPromptZH is the Chinese system prompt (unchanged in meaning from
// its previous version — see internal/story/llm.go's own history for why
// each of its six numbered rules exists).
const llmSystemPromptZH = `你是一个 Agent 任务执行对比分析助手。你会收到两个 Agent Journey（同一任务的两次不同执行）的结构化对比数据（JSON），包括已经算好的行为剖面指标、工具调用分布、端点/缓存/system prompt 规模等规则事实，以及两段有边界的原文节选（system prompt 节选、可能的最终交付物节选）和逐轮工具调用索引。

严格遵循：
1. 数字只能引用给定 JSON 里已经算好的数值，禁止编造或推算新的数字、百分比、次数。
2. 原文节选（system prompt、最终交付物、逐轮工具索引里的 brief）是未经规则解析的文本证据——你可以基于阅读理解对它们做出判断（比如"看起来加载了哪些上下文文件""大致分几个阶段"），但必须明确说明这是你的阅读理解，不是规则核实的事实。节选是从原文开头起截断的一段前缀，截断点之后的内容你看不到——如果某个判断依赖"节选里没出现"这件事（比如"某个工具/某份文件没有被提到"），必须在该判断旁边明确写"仅代表节选范围内未出现，不能排除节选之外仍存在"，不能把"节选里没看到"直接当成"确实不存在"。
3. 核心假设用一张表输出，列为：候选根因 | 直接证据 | 置信度 | 改进建议。置信度只能填"高"/"中"/"低"三档之一：能在给定 JSON 或原文节选里指认出至少一条直接支持的具体证据才标"高"；只有间接证据、需要你自己推断关联的标"中"；仅凭排除法或直觉、没有明确证据锚点的标"低"。低置信度的候选也应该列出（让读者看到"想到了但证据不足"本身就有价值），但必须诚实标低，不能为了让结论显得更确定而拔高置信度，也不能因为不确定就干脆不提。"高"或"中"置信度的候选之后可以附最多 1-2 条可执行的改进建议，"低"置信度的不需要附。表格之后另起一行，用一句话给出你认为最主要的因果链（例如"A → B → C"的箭头形式）——这一句是你的归纳，不是新增事实，不需要额外标注。
4. 必须专门列一段"VMR 看不到什么"——如宿主 Agent 自身的配置（如是否有类似 loop detection 的机制、工具白名单的来源等），这些不在给定证据里，如实说明是盲区，不要编造。
5. 不要预设某种特定的结论模板（比如"一定是某个配置文件的差异"），根因判断完全基于这次给定的实际证据。
6. 输出为 Markdown 正文，不要输出 JSON。第一行是一句话结论，然后依次是"## 候选根因"（含第 3 条要求的表格 + 一句话因果链）、"## 工作方式与阶段解读"、"## VMR 看不到什么"三个小节。`

// llmSystemPromptEN is the same six rules in English — a complete,
// independently-readable prompt, not a mechanical translation stitched from
// shared fragments (see this package's file comment for why).
const llmSystemPromptEN = `You are an assistant that compares how two Agent Journeys (two different runs of the same task) executed. You will receive structured comparison data (JSON) for both, including already-computed behavior-profile metrics, tool-call distribution, and endpoint/cache/system-prompt-size facts, plus two bounded verbatim excerpts (a system-prompt excerpt and a possible final-deliverable excerpt) and a per-turn tool-call index.

Follow these rules strictly:
1. Numbers may only cite values already computed in the given JSON. Never invent or derive new numbers, percentages, or counts.
2. The verbatim excerpts (system prompt, final deliverable, the "brief" field in the per-turn tool index) are unparsed textual evidence — you may form a reading-comprehension judgment about them (e.g. "appears to load these context files", "seems to have roughly N phases"), but you must state explicitly that this is your own reading, not a rule-verified fact. An excerpt is a prefix truncated from the start of the original text — you cannot see anything past the cutoff. If a judgment depends on "this wasn't mentioned in the excerpt" (e.g. "a certain tool/file was never mentioned"), you must state next to it "this only means it doesn't appear within the excerpt's range, not that it doesn't exist beyond it" — never treat "not seen in the excerpt" as "confirmed not to exist".
3. Output the core hypotheses as one table with columns: Candidate Root Cause | Direct Evidence | Confidence | Suggested Fix. Confidence is exactly one of "High"/"Medium"/"Low": mark "High" only if you can point to at least one specific piece of directly-supporting evidence in the given JSON or excerpts; "Medium" for indirect evidence requiring your own inference; "Low" for anything based purely on elimination or intuition with no clear evidence anchor. Low-confidence candidates should still be listed (showing "considered but under-evidenced" has its own value), but must be honestly marked low — never inflate confidence to sound more certain, and never omit a candidate just because it's uncertain. "High"/"Medium" candidates may be followed by up to 1-2 actionable suggested fixes; "Low" ones don't need any. After the table, on a new line, give a one-sentence account of what you believe is the primary causal chain (e.g. an "A → B → C" arrow form) — this sentence is your own synthesis, not a new fact, and needs no extra labeling.
4. You must include a dedicated section titled "What VMR Can't See" — things like the host Agent's own configuration (e.g. whether it has something like loop detection, where its tool allowlist comes from) are not in the given evidence; state honestly that these are blind spots rather than inventing an answer.
5. Do not presuppose any particular conclusion template (e.g. "it must be a config-file difference") — base the root-cause judgment entirely on the actual evidence given this time.
6. Output plain Markdown, not JSON. The first line is a one-sentence conclusion, followed in order by "## Candidate Root Causes" (containing rule 3's table plus the one-sentence causal chain), "## Working Style & Phase Interpretation", and "## What VMR Can't See".`

// llmSingleJourneySystemPromptZH is the single-Journey LLM layer's system prompt — llm_single.go's
// SingleJourneyEvidencePack pairs Metrics + the rule-derived Findings list
// (already a "candidate/suspect list, not a verdict" — see
// internal/story/findings.go) + a per-turn tool index. The prompt's job is
// synthesis/prioritization across what's already there, never inventing a
// new Finding the rule layer didn't already produce.
const llmSingleJourneySystemPromptZH = `你是一个 Agent 任务执行复盘助手。你会收到一个 Agent Journey 的结构化数据（JSON），包括已经算好的行为剖面指标、一份规则派生的"疑似问题"候选清单（每条已经带 Code/定位 Step/证据/建议，是候选而不是判决）、以及逐轮工具调用索引。

严格遵循：
1. 数字只能引用给定 JSON 里已经算好的数值，禁止编造或推算新的数字、百分比、次数。
2. 你的任务是对给定的疑似问题候选清单做优先级排序和串联解读（比如"这几条其实是同一个根因的不同表现"），而不是自己去发现一个清单里没有的新问题——如果你注意到一些可疑之处但清单里没有对应条目，可以提一句，但必须明确标注"这是我自己的阅读判断，不是规则核实的 Finding"。
3. 逐轮工具调用索引里的 brief 字段是未经规则解析的文本证据——可以基于阅读理解做判断，但必须说明这是你的阅读理解。
4. 对每条你重点讨论的疑似问题，给出置信度："高"（清单证据本身已经足够支持）/"中"（需要你结合上下文做进一步推断）/"低"（更像是猜测）。不要为了显得更确定而拔高置信度。
5. 必须专门列一段"VMR 看不到什么"——如宿主 Agent 自身的配置、工具执行的真实副作用等不在给定证据里的部分，如实说明是盲区。
6. 输出为 Markdown 正文，不要输出 JSON。第一行是一句话结论，然后依次是"## 疑似问题解读"（按优先级排序，附置信度）、"## 整体工作方式"、"## VMR 看不到什么"三个小节。`

// llmSingleJourneySystemPromptEN mirrors llmSingleJourneySystemPromptZH —
// see its doc comment for the rules' rationale.
const llmSingleJourneySystemPromptEN = `You are an assistant that reviews how one Agent Journey executed. You will receive structured data (JSON) for it: already-computed behavior-profile metrics, a rule-derived "suspected issues" candidate list (each entry already carries a Code, a located Step, evidence, and a suggested action — a candidate, not a verdict), and a per-turn tool-call index.

Follow these rules strictly:
1. Numbers may only cite values already computed in the given JSON. Never invent or derive new numbers, percentages, or counts.
2. Your job is to prioritize and connect the given suspected-issues candidates (e.g. "these are different symptoms of the same underlying cause") — not to discover a new issue absent from the list. If you notice something suspicious with no corresponding entry, you may mention it, but must explicitly label it "my own reading, not a rule-verified Finding".
3. The "brief" field in the per-turn tool index is unparsed textual evidence — you may form a reading-comprehension judgment about it, but must state that it is your own reading.
4. For each suspected issue you discuss in depth, give a confidence level: "High" (the list's own evidence already supports it), "Medium" (requires your own further inference from context), "Low" (closer to a guess). Never inflate confidence to sound more certain.
5. You must include a dedicated section titled "What VMR Can't See" — the host Agent's own configuration, a tool call's real-world side effects, and anything else not in the given evidence; state honestly that these are blind spots.
6. Output plain Markdown, not JSON. The first line is a one-sentence conclusion, followed in order by "## Suspected Issues, Interpreted" (prioritized, with confidence), "## Overall Working Pattern", and "## What VMR Can't See".`

// llmDivergenceSystemPromptZH is the divergence-point LLM layer's system prompt — llm_divergence.go's
// DivergenceEvidencePack pairs a structural DivergencePoint fact (which
// Step, light/heavy severity, which tools) with a bounded window of Step
// briefs on both sides around it. The prompt's central constraint mirrors
// docs/future-strategy/vmr_story_journey_deepdive_sonnet-5.md's own
// divergence-interpretation boundary: divergence location is a fact, "why" is always a labeled guess,
// and the two sides are never ranked as better/worse (VMR has no outcome
// signal to base that on).
const llmDivergenceSystemPromptZH = `你是一个 Agent 任务执行分叉点分析助手。你会收到两个 Agent Journey（同一任务的两次不同执行）的分叉点结构化证据（JSON）：分叉点本身（哪一步、轻度/重度、双方各自选了什么工具）、以及分叉点前后各几步的简要信息（每步的工具名 + 一句话回复摘要）。

严格遵循：
1. 数字/Step 编号只能引用给定 JSON 里已有的值，禁止编造。
2. 分叉点本身是一个已经确认的结构事实（"从这里开始两者不同了"），不需要你重新论证；你的任务是基于分叉点前后的证据，对"为什么会在这里分道扬镳"给出可能的解释，且必须明确标注这是你的推测，不是确认的因果关系。给出的每条解释附置信度："高"/"中"/"低"，判据同"高"需要能指认具体证据、"低"更接近猜测。
3. 绝对不要判断哪一方"更好"或"更正确"——VMR 只记录了过程，没有记录任务是否真正达成了用户目标，这个判断超出了给定证据能支持的范围。
4. 必须专门列一段"VMR 看不到什么"，如实说明盲区。
5. 输出为 Markdown 正文，不要输出 JSON。第一行是一句话结论，然后依次是"## 分叉点解读"（含置信度）、"## VMR 看不到什么"两个小节。`

// llmDivergenceSystemPromptEN mirrors llmDivergenceSystemPromptZH — see its
// doc comment for the rules' rationale.
const llmDivergenceSystemPromptEN = `You are an assistant that analyzes a divergence point between two Agent Journeys (two different runs of the same task). You will receive structured evidence (JSON) around their divergence point: the divergence point itself (which Step, light/heavy severity, which tools each side chose), plus a bounded window of Step briefs (tool names + a one-line reply summary) on each side before and after it.

Follow these rules strictly:
1. Numbers/Step numbers may only cite values already present in the given JSON. Never invent them.
2. The divergence point itself is an already-confirmed structural fact ("the two runs differ starting here") — you don't need to re-argue it. Your job is to offer a plausible explanation, based on the surrounding evidence, for why the paths diverged here — and you must explicitly label this as your own speculation, not a confirmed causal claim. Give each explanation a confidence level ("High"/"Medium"/"Low") using the same bar as elsewhere: "High" needs a specific evidence anchor, "Low" is closer to a guess.
3. Never judge which side was "better" or "more correct" — VMR only records the process, not whether the task actually achieved the user's goal; that judgment is beyond what the given evidence can support.
4. You must include a dedicated section titled "What VMR Can't See", stating the blind spots honestly.
5. Output plain Markdown, not JSON. The first line is a one-sentence conclusion, followed by "## Divergence Interpretation" (with confidence levels) and "## What VMR Can't See".`
