// Ver 2026-08-28, by Sonnet 5

// Pairs with internal/story/render_compare_html.go — the single-page HTML
// comparison dashboard (`vmr analyze -compare a,b -html`). Fixed UI
// strings only.
package i18n

import "fmt"

// CompareHTMLText is the comparison dashboard's chrome, in one language.
type CompareHTMLText struct {
	DocTitle       string
	RedactedBanner string
	GeneratedNote  string
	Empty          string
	Redacted       func(runes int) string

	SectionSides string
	SectionDiff  string
	SectionLLM   string

	InitialInstruction string
	DivergenceNone     string
	DivergenceHeadline func(aStep, bStep int, task string) string
	DivergenceNote     string
	NoTools            string

	MetricCol string
	ToolCol   string

	EndpointsLabel   string
	EndpointsSame    string
	EndpointsDiffer  string
	CacheLabel       string
	CachePair        func(aFirst, aSteady, bFirst, bSteady string) string
	SysPromptLabel   string
	SysPromptPair    func(aTok string, aChg int, bTok string, bChg int) string
	DurationLabel    string
	DurationPair     func(aWall, aTerm, bWall, bTerm string) string
	NoTermination    string
	DeliverableLabel string
	DeliverableNone  string
	DeliverableAt    func(step int) string

	LLMDisclaimer      func(model string) string
	LLMScopeOverall    string
	LLMScopeDivergence string
	LLMCached          string
}

func CompareHTML(lang Lang) CompareHTMLText {
	if lang == ZH {
		return CompareHTMLText{
			DocTitle:       "Journey 对比",
			RedactedBanner: "脱敏模式：正文替换为长度占位；LLM 解读小节已隐去（它会逐字转述证据）。",
			GeneratedNote:  "由 vmr analyze 生成 · 单文件自包含 · 零外部依赖",
			Empty:          "（空）",
			Redacted:       func(n int) string { return fmt.Sprintf("‹text: %d chars›", n) },

			SectionSides: "两侧",
			SectionDiff:  "分岔与差异",
			SectionLLM:   "LLM 解读",

			InitialInstruction: "双侧初始指令",
			DivergenceNone:     "对齐前缀内两侧工具使用结构一致。",
			DivergenceHeadline: func(a, b int, task string) string {
				return fmt.Sprintf("从 A.Step %d / B.Step %d（任务「%s」）起，两侧工具使用结构分岔", a, b, task)
			},
			DivergenceNote: "仅为结构事实（哪些工具被调用），不是根因判断。",
			NoTools:        "（无工具调用）",

			MetricCol: "指标",
			ToolCol:   "工具",

			EndpointsLabel:  "端点",
			EndpointsSame:   "两侧一致",
			EndpointsDiffer: "两侧不同",
			CacheLabel:      "缓存命中率",
			CachePair: func(af, as, bf, bs string) string {
				return fmt.Sprintf("A 首轮 %s → 稳态 %s · B 首轮 %s → 稳态 %s", af, as, bf, bs)
			},
			SysPromptLabel: "系统提示词",
			SysPromptPair: func(at string, ac int, bt string, bc int) string {
				return fmt.Sprintf("A %s（变更 %d 次） · B %s（变更 %d 次）", at, ac, bt, bc)
			},
			DurationLabel: "墙钟 / 终止",
			DurationPair: func(aw, atm, bw, btm string) string {
				return fmt.Sprintf("A %s（%s） · B %s（%s）", aw, atm, bw, btm)
			},
			NoTermination:    "未知",
			DeliverableLabel: "最终产物",
			DeliverableNone:  "未产出单文件交付物",
			DeliverableAt:    func(s int) string { return fmt.Sprintf("Step %d 通过", s) },

			LLMDisclaimer: func(m string) string {
				return "以下为模型（" + m + "）对上方事实的解读，不是事实本身；只喂了规则派生的事实与有界文本节选。"
			},
			LLMScopeOverall:    "总体",
			LLMScopeDivergence: "分岔点",
			LLMCached:          "（缓存命中）",
		}
	}
	return CompareHTMLText{
		DocTitle:       "Journey comparison",
		RedactedBanner: "Redacted: bodies are length placeholders; the LLM interpretation section is omitted (it paraphrases evidence verbatim).",
		GeneratedNote:  "Generated by vmr analyze · single self-contained file · zero external dependencies",
		Empty:          "(empty)",
		Redacted:       func(n int) string { return fmt.Sprintf("‹text: %d chars›", n) },

		SectionSides: "The two sides",
		SectionDiff:  "Divergence & diff",
		SectionLLM:   "LLM interpretation",

		InitialInstruction: "Opening instruction (both sides)",
		DivergenceNone:     "Tool-use structure is identical across the aligned prefix.",
		DivergenceHeadline: func(a, b int, task string) string {
			return fmt.Sprintf("From A.Step %d / B.Step %d (task %q), the two sides' tool-use structure diverges", a, b, task)
		},
		DivergenceNote: "A structural fact (which tools were called) only, not a root-cause claim.",
		NoTools:        "(no tool calls)",

		MetricCol: "Metric",
		ToolCol:   "Tool",

		EndpointsLabel:  "Endpoints",
		EndpointsSame:   "same on both",
		EndpointsDiffer: "differ",
		CacheLabel:      "Cache hit ratio",
		CachePair: func(af, as, bf, bs string) string {
			return fmt.Sprintf("A first %s → steady %s · B first %s → steady %s", af, as, bf, bs)
		},
		SysPromptLabel: "System prompt",
		SysPromptPair: func(at string, ac int, bt string, bc int) string {
			return fmt.Sprintf("A %s (%d changes) · B %s (%d changes)", at, ac, bt, bc)
		},
		DurationLabel: "Wall clock / termination",
		DurationPair: func(aw, atm, bw, btm string) string {
			return fmt.Sprintf("A %s (%s) · B %s (%s)", aw, atm, bw, btm)
		},
		NoTermination:    "unknown",
		DeliverableLabel: "Final deliverable",
		DeliverableNone:  "no single-file deliverable produced",
		DeliverableAt:    func(s int) string { return fmt.Sprintf("Step %d via", s) },

		LLMDisclaimer: func(m string) string {
			return "Below is model " + m + "'s reading of the facts above — interpretation, not fact; it was fed only rule-derived facts and bounded text excerpts."
		},
		LLMScopeOverall:    "Overall",
		LLMScopeDivergence: "Divergence point",
		LLMCached:          "(cached)",
	}
}
